### ISSUE TITLE
Option to not select brackets on first grow

### ISSUE THREAD

**Issue by tgreen7** [closedcontour/very-smart-select#6]
This extension immediately selects the full function with brackets

<img width="250" alt="Screen Shot 2021-03-23 at 11 48 29 PM" src="https://user-images.githubusercontent.com/10415101/112267196-53603700-8c32-11eb-9112-40064326aeb5.png">

It would be nice if there was an option to first select everything within the brackets

<img width="242" alt="Screen Shot 2021-03-23 at 11 48 40 PM" src="https://user-images.githubusercontent.com/10415101/112267244-6541da00-8c32-11eb-83ce-b587dae77c93.png">

and then be able to expand to include the brackets with another `grow`. 

Maybe this could be a user setting for preference. This would be super useful for me.

**Comment by closedcontour** [comment]
I've stopped using this plugin since [the introduction of better, native SmartSelect](https://code.visualstudio.com/updates/v1_35#_smart-selection-for-javascript-and-typescript). I believe the native behavior does what you want.

**Comment by tgreen7** [comment]
Hmm. I actually like your extension better than the native. The native selects the whole function and takes a few more grows.  I might try to tackle this at some point if you are accepting prs.

**Comment by closedcontour** [comment]
I'd happily accept/merge a PR. Go for it!
